-- Optional recovery-code material on vault_meta. When all three columns
-- are non-NULL, vault_unlock_with_recovery can unwrap the vault key
-- without the master password. Generated by vault_generate_recovery_code
-- and overwritten on each regeneration; cleared on vault_reset.
ALTER TABLE vault_meta ADD COLUMN recovery_salt          BLOB;
ALTER TABLE vault_meta ADD COLUMN recovery_kdf_params    TEXT;
ALTER TABLE vault_meta ADD COLUMN recovery_wrapped_key   BLOB;
